# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'noteSoClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for noteSoClient

  pod 'React', path: '../node_modules/react-native', subspecs: [
    'ART',
  ]

  target 'noteSoClient-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'noteSoClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

